//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceDispensador.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PICA_DISPENSADOREntities : DbContext
    {
        public PICA_DISPENSADOREntities()
            : base("name=PICA_DISPENSADOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tATMs> tATMs { get; set; }
        public virtual DbSet<tCompositionDeviceATM> tCompositionDeviceATM { get; set; }
        public virtual DbSet<tDevice> tDevice { get; set; }
        public virtual DbSet<tDomain> tDomain { get; set; }
        public virtual DbSet<tNMDCommand> tNMDCommand { get; set; }
        public virtual DbSet<tNMDResponseCode> tNMDResponseCode { get; set; }
        public virtual DbSet<tTypeDevice> tTypeDevice { get; set; }
        public virtual DbSet<tConfigDevice> tConfigDevice { get; set; }
        public virtual DbSet<tConfigDispenserDevice> tConfigDispenserDevice { get; set; }
    
        public virtual ObjectResult<GetDispenserByATM_Result> GetDispenserByATM(Nullable<int> idATM)
        {
            var idATMParameter = idATM.HasValue ?
                new ObjectParameter("IdATM", idATM) :
                new ObjectParameter("IdATM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDispenserByATM_Result>("GetDispenserByATM", idATMParameter);
        }
    }
}
