//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceDispensador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tATMs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tATMs()
        {
            this.tCompositionDeviceATM = new HashSet<tCompositionDeviceATM>();
        }
    
        public int IdATM { get; set; }
        public string NrSerie { get; set; }
        public Nullable<int> IdOffice { get; set; }
        public string CodOffice { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Ubication { get; set; }
        public string Geolocation { get; set; }
        public string IP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCompositionDeviceATM> tCompositionDeviceATM { get; set; }
    }
}
