//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceDispensador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCompositionDeviceATM
    {
        public int IdCompositionDeviceATM { get; set; }
        public int IdDevice { get; set; }
        public int IdATM { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int Status { get; set; }
        public string Notes { get; set; }
    
        public virtual tATMs tATMs { get; set; }
        public virtual tDevice tDevice { get; set; }
    }
}
