//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceDispensador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDevice()
        {
            this.tCompositionDeviceATM = new HashSet<tCompositionDeviceATM>();
        }
    
        public int IdDevice { get; set; }
        public int IdTypeDevice { get; set; }
        public string NrSerie { get; set; }
        public string Firmware { get; set; }
        public Nullable<int> Status { get; set; }
        public string Notes { get; set; }
        public string Localization { get; set; }
        public string Store { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCompositionDeviceATM> tCompositionDeviceATM { get; set; }
        public virtual tTypeDevice tTypeDevice { get; set; }
        public virtual tConfigDevice tConfigDevice { get; set; }
    }
}
