//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceDispensador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDomain
    {
        public int IdTypeDevice { get; set; }
        public int IdDomain { get; set; }
        public string IdState { get; set; }
        public string DescState { get; set; }
        public string ValueNemo { get; set; }
    }
}
