//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceDispensador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNMDResponseCode
    {
        public int IdNMDResponseCode { get; set; }
        public int IdTypeDevice { get; set; }
        public int IdStatusCode { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
        public string Response { get; set; }
        public string TypeEnum { get; set; }
    
        public virtual tTypeDevice tTypeDevice { get; set; }
    }
}
