//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceDispensador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTypeDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTypeDevice()
        {
            this.tDevice = new HashSet<tDevice>();
            this.tNMDCommand = new HashSet<tNMDCommand>();
            this.tNMDResponseCode = new HashSet<tNMDResponseCode>();
        }
    
        public int IdTypeDevice { get; set; }
        public string Name { get; set; }
        public string Provider { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDevice> tDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNMDCommand> tNMDCommand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNMDResponseCode> tNMDResponseCode { get; set; }
        public virtual tConfigDispenserDevice tConfigDispenserDevice { get; set; }
    }
}
