//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostFingerControl.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFingerprint
    {
        public long IdFingerprint { get; set; }
        public string Description { get; set; }
        public byte[] CodeValue { get; set; }
        public long IdcFingerprintType { get; set; }
        public long IdPerson { get; set; }
        public Nullable<System.DateTime> RegisterDateInSystem { get; set; }
        public bool WithNewFormat { get; set; }
        public int FingerprintSize { get; set; }
        public long FormatType { get; set; }
    }
}
